# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Gradle
org.gradle.daemon                    = false
org.gradle.debug                     = false
org.gradle.jvmargs                   = -Xmx3G

# Plugins
fabric_loom_version                  = 1.6-SNAPSHOT
jetbrains_gradle_idea_ext_version    = 1.1.7
modmuss50_mod_publish_version        = 0.4.0
spongepowered_mixin_version          = 0.7-SNAPSHOT
spongepowered_vanilla_gradle_version = 0.2.1-SNAPSHOT
spotless_version                     = 6.25.0

# Common
java_version                         = 21
minecraft_version                    = 1.20.6

# NeoForge
neo_loader_version_range             = [3,)
mapping_channel                      = official
mapping_version                      = 1.20.6
minecraft_version_range              = [1.20.6, 1.21)
neo_gradle_userdev_version           = 7.0.138
neo_version                          = 20.6.110-beta
neo_version_range                    = [20,)

# Fabric
fabric_loader_version                = 0.15.11
fabric_version                       = 0.99.4+1.20.6
modmenu_version                      = 10.0.0-beta.1

# Mod Options
curseforge_id                        = 912767
group                                = mod.azure.azurelibarmor
maven_name                           = azurelibarmor
maven_url                            = https://libs.azuredoom.com:4443/mods
mod_author                           = AzureDoom
mod_credits                          = AzureDoom, Gecko, Eliot, Chappie, DerToaster, Tslat, Bvanseg
mod_description                      = Based off Geckolib but now just for my own needs.
mod_id                               = azurelibarmor
mod_issues                           = https://github.com/AzureDoom/AzureLib-Armor/issues
mod_license                          = MIT
mod_logo                             = azurelib.png
mod_name                             = AzureLib Armor
mod_sources                          = https://github.com/AzureDoom/AzureLib
mod_url                              = https://github.com/AzureDoom/AzureLib-Armor
version                              = 2.2.2
modrinth_id                          = pduQXSbl