modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/AzureDoom/AzureLib-Armor/issues"
license="MIT"
[[mods]]
modId="azurelibarmor"
version="${file.jarVersion}" 
displayName="AzureLib Armor"
displayURL="ttps://modrinth.com/mod/azurelib-armor"
logoFile="azurelib.png" 
credits="AzureDoom, Gecko, Eliot, DerToaster, Tslat, Bvanseg"
authors="AzureDoom, Gecko, Eliot, Chappie, DerToaster, Tslat, Bvanseg"
description='''
A striped down Azurelib just for Armor!
'''
[[dependencies.azurelibarmor]]
    modId="forge"
    mandatory=true 
    versionRange="[47.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.azurelibarmor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1, 1.20.2)"
    ordering="NONE"
    side="BOTH"
